# Generated by Django 4.1.7 on 2023-04-05 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]+$')], verbose_name='name'),
        ),
    ]
